const jsConvert = require('../../index');
const obj = require('./object');

console.log(jsConvert.lowerKeys(obj));
console.log('============================================');
console.log(jsConvert.lowerKeys(obj, { recursive: true }));

/**
{ camelcase: 1,
  uppercase: 2,
  lowercase: 3,
  snake_case: 4,
  pascalcase: 5,
  'title case': 6,
  'dot.case': 7,
  'param-case': 8,
  'sentence case': 9,
  'path/case': 10,
  'header-case': 11,
  lv11:
   { camelCase: 1,
     UPPERCASE: 2,
     lowercase: 3,
     snake_case: 4,
     PascalCase: 5,
     'Title Case': 6,
     'dot.case': 7,
     'param-case': 8,
     'Sentence case': 9,
     'path/case': 10,
     'Header-Case': 11 },
  lv12:
   { camelCase: 1,
     UPPERCASE: 2,
     lowercase: 3,
     snake_case: 4,
     PascalCase: 5,
     'Title Case': 6,
     'dot.case': 7,
     'param-case': 8,
     'Sentence case': 9,
     'path/case': 10,
     'Header-Case': 11,
     lv21:
      { camelCase: 1,
        UPPERCASE: 2,
        lowercase: 3,
        snake_case: 4,
        PascalCase: 5,
        'Title Case': 6,
        'dot.case': 7,
        'param-case': 8,
        'Sentence case': 9,
        'path/case': 10,
        'Header-Case': 11,
        lv31: [Object],
        lv32: [Object] },
     lv22:
      { camelCase: 1,
        UPPERCASE: 2,
        lowercase: 3,
        snake_case: 4,
        PascalCase: 5,
        'Title Case': 6,
        'dot.case': 7,
        'param-case': 8,
        'Sentence case': 9,
        'path/case': 10,
        'Header-Case': 11 } } }
============================================
{ camelcase: 1,
  uppercase: 2,
  lowercase: 3,
  snake_case: 4,
  pascalcase: 5,
  'title case': 6,
  'dot.case': 7,
  'param-case': 8,
  'sentence case': 9,
  'path/case': 10,
  'header-case': 11,
  lv11:
   { camelcase: 1,
     uppercase: 2,
     lowercase: 3,
     snake_case: 4,
     pascalcase: 5,
     'title case': 6,
     'dot.case': 7,
     'param-case': 8,
     'sentence case': 9,
     'path/case': 10,
     'header-case': 11 },
  lv12:
   { camelcase: 1,
     uppercase: 2,
     lowercase: 3,
     snake_case: 4,
     pascalcase: 5,
     'title case': 6,
     'dot.case': 7,
     'param-case': 8,
     'sentence case': 9,
     'path/case': 10,
     'header-case': 11,
     lv21:
      { camelcase: 1,
        uppercase: 2,
        lowercase: 3,
        snake_case: 4,
        pascalcase: 5,
        'title case': 6,
        'dot.case': 7,
        'param-case': 8,
        'sentence case': 9,
        'path/case': 10,
        'header-case': 11,
        lv31: [Object],
        lv32: [Object] },
     lv22:
      { camelcase: 1,
        uppercase: 2,
        lowercase: 3,
        snake_case: 4,
        pascalcase: 5,
        'title case': 6,
        'dot.case': 7,
        'param-case': 8,
        'sentence case': 9,
        'path/case': 10,
        'header-case': 11 } } }
 */
