const jsConvert = require('../../index');
const obj = require('./object');

console.log(jsConvert.pascalKeys(obj));
console.log('============================================');
console.log(jsConvert.pascalKeys(obj, { recursive: true }));

/**
{ CamelCase: 1,
  Uppercase: 2,
  Lowercase: 3,
  SnakeCase: 4,
  PascalCase: 5,
  TitleCase: 6,
  DotCase: 7,
  ParamCase: 8,
  SentenceCase: 9,
  PathCase: 10,
  HeaderCase: 11,
  Lv11:
   { camelCase: 1,
     UPPERCASE: 2,
     lowercase: 3,
     snake_case: 4,
     PascalCase: 5,
     'Title Case': 6,
     'dot.case': 7,
     'param-case': 8,
     'Sentence case': 9,
     'path/case': 10,
     'Header-Case': 11 },
  Lv12:
   { camelCase: 1,
     UPPERCASE: 2,
     lowercase: 3,
     snake_case: 4,
     PascalCase: 5,
     'Title Case': 6,
     'dot.case': 7,
     'param-case': 8,
     'Sentence case': 9,
     'path/case': 10,
     'Header-Case': 11,
     lv21:
      { camelCase: 1,
        UPPERCASE: 2,
        lowercase: 3,
        snake_case: 4,
        PascalCase: 5,
        'Title Case': 6,
        'dot.case': 7,
        'param-case': 8,
        'Sentence case': 9,
        'path/case': 10,
        'Header-Case': 11,
        lv31: [Object],
        lv32: [Object] },
     lv22:
      { camelCase: 1,
        UPPERCASE: 2,
        lowercase: 3,
        snake_case: 4,
        PascalCase: 5,
        'Title Case': 6,
        'dot.case': 7,
        'param-case': 8,
        'Sentence case': 9,
        'path/case': 10,
        'Header-Case': 11 } } }
============================================
{ CamelCase: 1,
  Uppercase: 2,
  Lowercase: 3,
  SnakeCase: 4,
  PascalCase: 5,
  TitleCase: 6,
  DotCase: 7,
  ParamCase: 8,
  SentenceCase: 9,
  PathCase: 10,
  HeaderCase: 11,
  Lv11:
   { CamelCase: 1,
     Uppercase: 2,
     Lowercase: 3,
     SnakeCase: 4,
     PascalCase: 5,
     TitleCase: 6,
     DotCase: 7,
     ParamCase: 8,
     SentenceCase: 9,
     PathCase: 10,
     HeaderCase: 11 },
  Lv12:
   { CamelCase: 1,
     Uppercase: 2,
     Lowercase: 3,
     SnakeCase: 4,
     PascalCase: 5,
     TitleCase: 6,
     DotCase: 7,
     ParamCase: 8,
     SentenceCase: 9,
     PathCase: 10,
     HeaderCase: 11,
     Lv21:
      { CamelCase: 1,
        Uppercase: 2,
        Lowercase: 3,
        SnakeCase: 4,
        PascalCase: 5,
        TitleCase: 6,
        DotCase: 7,
        ParamCase: 8,
        SentenceCase: 9,
        PathCase: 10,
        HeaderCase: 11,
        Lv31: [Object],
        Lv32: [Object] },
     Lv22:
      { CamelCase: 1,
        Uppercase: 2,
        Lowercase: 3,
        SnakeCase: 4,
        PascalCase: 5,
        TitleCase: 6,
        DotCase: 7,
        ParamCase: 8,
        SentenceCase: 9,
        PathCase: 10,
        HeaderCase: 11 } } }
 */
