const jsConvert = require('../../index');
const obj = require('./object');

console.log(jsConvert.snakeKeys(obj));
console.log('============================================');
console.log(jsConvert.snakeKeys(obj, { recursive: true }));

/**
{ camel_case: 1,
  uppercase: 2,
  lowercase: 3,
  snake_case: 4,
  pascal_case: 5,
  title_case: 6,
  dot_case: 7,
  param_case: 8,
  sentence_case: 9,
  path_case: 10,
  header_case: 11,
  lv11:
   { camelCase: 1,
     UPPERCASE: 2,
     lowercase: 3,
     snake_case: 4,
     PascalCase: 5,
     'Title Case': 6,
     'dot.case': 7,
     'param-case': 8,
     'Sentence case': 9,
     'path/case': 10,
     'Header-Case': 11 },
  lv12:
   { camelCase: 1,
     UPPERCASE: 2,
     lowercase: 3,
     snake_case: 4,
     PascalCase: 5,
     'Title Case': 6,
     'dot.case': 7,
     'param-case': 8,
     'Sentence case': 9,
     'path/case': 10,
     'Header-Case': 11,
     lv21:
      { camelCase: 1,
        UPPERCASE: 2,
        lowercase: 3,
        snake_case: 4,
        PascalCase: 5,
        'Title Case': 6,
        'dot.case': 7,
        'param-case': 8,
        'Sentence case': 9,
        'path/case': 10,
        'Header-Case': 11,
        lv31: [Object],
        lv32: [Object] },
     lv22:
      { camelCase: 1,
        UPPERCASE: 2,
        lowercase: 3,
        snake_case: 4,
        PascalCase: 5,
        'Title Case': 6,
        'dot.case': 7,
        'param-case': 8,
        'Sentence case': 9,
        'path/case': 10,
        'Header-Case': 11 } } }
============================================
{ camel_case: 1,
  uppercase: 2,
  lowercase: 3,
  snake_case: 4,
  pascal_case: 5,
  title_case: 6,
  dot_case: 7,
  param_case: 8,
  sentence_case: 9,
  path_case: 10,
  header_case: 11,
  lv11:
   { camel_case: 1,
     uppercase: 2,
     lowercase: 3,
     snake_case: 4,
     pascal_case: 5,
     title_case: 6,
     dot_case: 7,
     param_case: 8,
     sentence_case: 9,
     path_case: 10,
     header_case: 11 },
  lv12:
   { camel_case: 1,
     uppercase: 2,
     lowercase: 3,
     snake_case: 4,
     pascal_case: 5,
     title_case: 6,
     dot_case: 7,
     param_case: 8,
     sentence_case: 9,
     path_case: 10,
     header_case: 11,
     lv21:
      { camel_case: 1,
        uppercase: 2,
        lowercase: 3,
        snake_case: 4,
        pascal_case: 5,
        title_case: 6,
        dot_case: 7,
        param_case: 8,
        sentence_case: 9,
        path_case: 10,
        header_case: 11,
        lv31: [Object],
        lv32: [Object] },
     lv22:
      { camel_case: 1,
        uppercase: 2,
        lowercase: 3,
        snake_case: 4,
        pascal_case: 5,
        title_case: 6,
        dot_case: 7,
        param_case: 8,
        sentence_case: 9,
        path_case: 10,
        header_case: 11 } } }
 */
